# prj.conf (LPC55S69)

# Enable serial drivers
CONFIG_SERIAL=y

# Enable console for standard debug prints (printf/printk)
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

# Enable floating-point formatting for printf/snprintf
CONFIG_CBPRINTF_FP_SUPPORT=y
